var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/client-portal/setup/[invite]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1uh_ir3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_76o57._.js")
R.c("server/chunks/ssr/node_modules_1qtodoz._.js")
R.c("server/chunks/ssr/_18t4a54._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/app_global-error_tsx_0w002m_._.js")
R.c("server/chunks/ssr/_next-internal_server_app_client-portal_setup_[invite]_page_actions_1xa_z8a.js")
R.m(81402)
module.exports=R.m(81402).exports
