# Generated by Django 6.0.8 on 2026-09-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(default='Shoot Planning', max_length=40)),
                ('raw_status', models.CharField(default='Pending', max_length=30)),
                ('editing_status', models.CharField(default='Not Started', max_length=30)),
                ('album_status', models.CharField(default='Not Started', max_length=30)),
                ('video_status', models.CharField(default='Not Started', max_length=30)),
                ('delivery_status', models.CharField(default='Pending', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('client_approved_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_job', to='sales.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
