# Generated by Django 6.0.8 on 2026-09-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='album_delivery_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='client_approval_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='photo_delivery_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='video_delivery_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
