# Generated by Django 6.0.8 on 2026-09-02 22:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('production', '0003_productionjob_album_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=120)),
                ('activity_date', models.DateField(default=django.utils.timezone.localdate)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='production.productionjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('activity_type', 'Overdue Reminder')), fields=('organization', 'job', 'activity_type', 'activity_date'), name='unique_daily_production_reminder')],
            },
        ),
    ]
