# Generated by Django 6.0.8 on 2026-09-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(default='Shoot', max_length=80)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='Scheduled', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('slotted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
