# Generated by Django 6.0.8 on 2026-09-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='assistant',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='bts',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='candid',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='cinematic',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='client_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='contact_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='couple_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='date_status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='drone',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='handled_by',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='photo',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='tbd_month',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='video',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PhotographerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('mobile', models.CharField(blank=True, max_length=40)),
                ('living_in', models.CharField(blank=True, max_length=120)),
                ('work', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(default='Available', max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
