# Generated by Django 6.0.8 on 2026-09-03 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizationauditactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='transactional', max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('recipient', models.CharField(max_length=255)),
                ('delivered', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='core.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'category', 'created_at'], name='core_emaill_organiz_db7217_idx')],
            },
        ),
    ]
