#!/usr/bin/env node
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, "..");

const API_URL = process.env.PLAYWRIGHT_API_URL ?? "http://127.0.0.1:8000";
const SCHEMA_URL = `${API_URL}/api/schema/`;
const OUT_FILE = resolve(projectRoot, "lib", "api-types.ts");

const banner = `// AUTOGENERATED — DO NOT EDIT
// Regenerate with: npm run api:codegen
// Source: ${SCHEMA_URL}
// Generated at: ${new Date().toISOString()}

`;

async function main() {
  process.stdout.write(`Fetching OpenAPI schema from ${SCHEMA_URL}…\n`);
  const ast = await openapiTS(new URL(SCHEMA_URL));
  const body = astToString(ast);
  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, banner + body + "\n", "utf8");
  process.stdout.write(`Wrote ${OUT_FILE} (${body.length} bytes)\n`);
}

main().catch((error) => {
  process.stderr.write(`openapi-codegen failed: ${error.message}\n`);
  process.exit(1);
});
