module.exports=[51896,a=>{"use strict";a.s(["GlobalErrorBoundary",()=>b]);let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call GlobalErrorBoundary() from the server but GlobalErrorBoundary is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/GlobalErrorBoundary.tsx","GlobalErrorBoundary")},17177,a=>{"use strict";var b=a.i(51896);a.n(b)},33290,a=>{"use strict";var b=a.i(7997),c=a.i(22194),d=a.i(16219),e=a.i(78164),f=a.i(17177);let g=`(() => {
  try {
    const stored = localStorage.getItem('lenspire-theme');
    if (stored === 'light' || stored === 'dark') {
      document.documentElement.dataset.theme = stored;
      document.documentElement.style.colorScheme = stored;
      return;
    }
    const host = window.location.hostname;
    const theme = host === 'crm.lenspireai.com' ? 'light' : 'dark';
    document.documentElement.dataset.theme = theme;
    document.documentElement.style.colorScheme = theme;
  } catch (e) {
    document.documentElement.dataset.theme = 'light';
    document.documentElement.style.colorScheme = 'light';
  }
})();`;a.s(["default",0,function({children:a}){return(0,b.jsxs)("html",{lang:"en",suppressHydrationWarning:!0,children:[(0,b.jsx)("head",{children:(0,b.jsx)("script",{dangerouslySetInnerHTML:{__html:g}})}),(0,b.jsx)("body",{suppressHydrationWarning:!0,children:(0,b.jsx)(f.GlobalErrorBoundary,{children:(0,b.jsx)(d.QueryProvider,{children:(0,b.jsxs)(e.ThemeProvider,{children:[(0,b.jsx)(c.ServiceWorkerRegister,{}),a]})})})})]})},"metadata",0,{title:"LenspireCRM Pro",description:"Photography studio CRM for sales, operations, accounts, and production.",applicationName:"LenspireCRM Pro",appleWebApp:{capable:!0,title:"LenspireCRM",statusBarStyle:"black-translucent"},formatDetection:{telephone:!1}},"viewport",0,{themeColor:"#7c3aed",width:"device-width",initialScale:1}])},70864,function(a){a.n(a.i(33290))},479,a=>{"use strict";a.s(["QueryProvider",()=>b]);let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call QueryProvider() from the server but QueryProvider is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/QueryProvider.tsx","QueryProvider")},16219,a=>{"use strict";var b=a.i(479);a.n(b)},5776,a=>{"use strict";a.s(["ServiceWorkerRegister",()=>b]);let b=(0,a.i(11857).registerClientReference)(function(){throw Error("Attempted to call ServiceWorkerRegister() from the server but ServiceWorkerRegister is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/ServiceWorkerRegister.tsx","ServiceWorkerRegister")},22194,a=>{"use strict";var b=a.i(5776);a.n(b)},40314,a=>{"use strict";a.s(["ThemeProvider",()=>c,"ThemeToggle",()=>d,"useTheme",()=>e]);var b=a.i(11857);let c=(0,b.registerClientReference)(function(){throw Error("Attempted to call ThemeProvider() from the server but ThemeProvider is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/ThemeToggle.tsx","ThemeProvider"),d=(0,b.registerClientReference)(function(){throw Error("Attempted to call ThemeToggle() from the server but ThemeToggle is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/ThemeToggle.tsx","ThemeToggle"),e=(0,b.registerClientReference)(function(){throw Error("Attempted to call useTheme() from the server but useTheme is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.")},"[project]/components/ThemeToggle.tsx","useTheme")},78164,a=>{"use strict";var b=a.i(40314);a.n(b)}];

//# sourceMappingURL=_18t4a54._.js.map