# Generated by Django 6.0.8 on 2026-09-02 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_booking_advances'),
        ('core', '0001_initial'),
        ('sales', '0003_salestarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(max_length=40)),
                ('milestone_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('action', models.CharField(default='Copied', max_length=30)),
                ('reminder_date', models.DateField(default=django.utils.timezone.localdate)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='sales.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='sales.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ('-reminder_date', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'booking', 'payment_type', 'reminder_date'), name='unique_daily_payment_reminder')],
            },
        ),
    ]
