/** Creates readable, filesystem-safe names for files generated by the CRM. */
export function exportFilename(label: string, extension: "xlsx" | "csv") {
  const now = new Date();
  const pad = (value: number) => String(value).padStart(2, "0");
  const timestamp = [
    now.getFullYear(),
    pad(now.getMonth() + 1),
    pad(now.getDate()),
  ].join("-") + "_" + [
    pad(now.getHours()),
    pad(now.getMinutes()),
    pad(now.getSeconds()),
  ].join("-");

  return `${label}_${timestamp}.${extension}`;
}
