# Generated by Django 6.0.8 on 2026-09-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_code', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('event_type', models.CharField(max_length=80)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='New', max_length=30)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('next_followup_at', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_code', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=80)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('package_name', models.CharField(default='Custom Package', max_length=120)),
                ('quoted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(default='Confirmed', max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='sales.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.lead')),
            ],
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=120)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='sales.lead')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('organization', 'lead_code'), name='unique_org_lead_code'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'customer_code'), name='unique_org_customer_code'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('organization', 'booking_code'), name='unique_org_booking_code'),
        ),
    ]
