# Generated by Django 6.0.8 on 2026-09-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='advance_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='lead',
            name='couple_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='received_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='referral_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lead',
            name='referred_by',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='lead',
            name='total_closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='wedding_dates',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
