# Generated by Django 6.0.8 on 2026-09-02 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0002_lead_advance_received_lead_client_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.CharField(max_length=120)),
                ('target_month', models.CharField(max_length=7)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('target_bookings', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'salesperson', 'target_month'), name='unique_org_sales_target')],
            },
        ),
    ]
